### ISSUE TITLE
pwned-sqlite3

### ISSUE THREAD

**Issue by Uzlopak** [wKovacs64/pwned#167]
Hi, 

I wanted to introduce my pwned-sqlite3 package to you. 

Should we cross reference our products in the README.md?

**Comment by wKovacs64** [comment]
Hey @Uzlopak, thanks for your interest in this project and congratulations on starting pwned-sqlite3! I don't plan to list any external projects in the README at this time (other than the source material) as there are too many in the ecosystem to count.

Best of luck to you!

**Comment by Uzlopak** [comment]
Thanks for your feedback :).
