### ISSUE TITLE
[OUTPUT] 'pwned pw' output cannot be redirected or piped in Bash

### ISSUE THREAD

**Issue by ledoux11u** [wKovacs64/pwned#17]
I use pwned into a set of tools and I need to parse all tools commands outputs.

When I run for example 'pwned ba _email_' I'm able to parse the result output correctly.
But, with the password option (pwned pw _password_) I cannot pipe or redirect anything,  the output is always empty.

For example :

"pwned pw qwerty | grep -o 'times' " will not output grep results as expected.

"pwned pw qwerty &> /tmp/test" will results with an empty file.

I suspect that the cause of this issue is the special character present at the beginning of the output ( ⚠ or ✔ ) but I'm not sure.

I'm using Debian 9 stable and Bash as shell.

Hope you can reproduce the issue and find a reliable solution.

**Comment by wKovacs64** [comment]
Hi @ledoux11u, thanks for your interest in the project!

Your use case is essentially what I had in mind with "raw" mode which can be enabled with `--raw` or `-r`. Can you try that and see if accomplishes what you need?

`pwned pw -r qwerty | grep -o 'times' `

**Comment by ledoux11u** [comment]
Hi !
Yes it's working well now ! Thanks for your fast answer.
"-r" option isn't documented in "pwned -h" and I didn't read carefully Github docs ^^.

Sorry for inconvenience.
Closed Issue.

**Comment by wKovacs64** [comment]
Great, I'm glad that worked for you!

FWIW, it doesn't show up in the top-level help (`pwned -h`) because it's a command-level option. It shows up in `pwned pw -h` instead.
