### ISSUE TITLE
✖ Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Fabiandenise** [wKovacs64/pwned#175]
──(kali㉿kali)-[~/pwned]
─$ npx pwned breaches -d adobe.com                                                                                                                      1 ⨯
✖ Service Temporarily Unavailable
──(kali㉿kali)-[~/pwned]
└─$ npx pwned ba pleasebeclean@fingerscrossed.tld    
✖ Service Temporarily Unavailable

**Comment by wKovacs64** [comment]
That sounds like a network issue on your end, unfortunately. Your examples are working for me. Does curl work?

```
curl "https://haveibeenpwned.com/api/v3/breaches?domain=adobe.com"
```

**Comment by Fabiandenise** [comment]
yeah i find issue, vpn lock it. tx
