### ISSUE TITLE
failed to the run pwned in cmdline

### ISSUE THREAD

**Issue by victordetoni** [wKovacs64/pwned#203]
root@Victor:/home/victor# pwned
/usr/local/lib/node_modules/pwned/bin/pwned.js:3
import { fileURLToPath } from 'url';
       ^

**Comment by wKovacs64** [comment]
Sorry, not sure how I missed this issue. 🙈

I'm guessing you were trying to run the latest version of `pwned` (v10) on some older version of Node (pwned v10 requires Node 14.13.1 or >= 16.0.0). If this is still a problem, please reopen with more details (operating system, Node version, pwned version, etc.). 

Thank you for your interest in the project!
