### ISSUE TITLE
Error when running any command

### ISSUE THREAD

**Issue by ItsYoDog** [wKovacs64/pwned#217]
Trying to run any command or even just "pwned" in the terminal results in the following error:
```js
file:///usr/local/lib/node_modules/pwned/node_modules/conf/dist/source/index.js:109
                if (value?.default) {
                          ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```

Yes, I've tried running using sudo and even root, but it still gives me the error.
I've also tried older versions of nodejs as it gives warnings that the nodejs version used in this code is waay outdates (like 4 entire versions back) with no result.

**Comment by wKovacs64** [comment]
Which version of Node.js are you running (`node -v`)? Sounds old. The latest version of pwned (v11) requires Node.js v16 or higher. If you're on an older version than that, you either need to upgrade your Node version to something >=16 or use an older version of pwned. See the [releases](https://github.com/wKovacs64/pwned/releases) page for a log of when support for various Node versions was dropped.
