### ISSUE TITLE
Failed to query

### ISSUE THREAD

**Issue by shaolinint** [wKovacs64/pwned#22]
# npx pwned
pwned <command>

Commands:
  pwned ba <account|email>      get all breaches for an account (username or email address)
  pwned breach <name>           get a single breached site by breach name
  pwned breaches                get all breaches in the system
  pwned dc                      get all data classes in the system
  pwned pa <email>              get all pastes for an account (email address)
  pwned pw <password>           securely check a password for public exposure
  pwned search <account|email>  search breaches and pastes for an account (username or email
                                address)

Options:
  -h, --help     Show help                                                                 [boolean]
  -v, --version  Show version number                                                       [boolean]

Not enough non-option arguments: got 0, need at least 1
# npx pwned breach xxxx.com
✖ (0 , _hibp.breach) is not a function
# pwned ba xxxx@gmail.com    
✖ (0 , _hibp.breachedAccount) is not a function

**Comment by wKovacs64** [comment]
This should be resolved now, thank you for the bug report @shaolinint.
