### ISSUE TITLE
IP(?) block

### ISSUE THREAD

**Issue by Peneheals** [wKovacs64/pwned#30]
After the first query I got:

```
$ npx pwned ba mail@example.com
npx: installed 85 in 9.007s
✖ Request blocked, contact haveibeenpwned.com if this continues (Ray ID: xxxxxxxxxxxxxxxx-BUD)
```

Maybe I'm really blocked? That was my first try :) If yes, I'm gonna reach hibp directly.

**Comment by wKovacs64** [comment]
Hey @Peneheals - it's not yet clear why, but yes, it appears like you are actually blocked. That same command works fine for me.

**Comment by wKovacs64** [comment]
Out of curiosity, could you try `npx pwned pa mail@example.com` and see if that works? I think the blocking rules are tighter on the `breachedaccount` endpoint, which affects `pwned ba` and `pwned search` but not the other commands.

**Comment by Peneheals** [comment]
You are right, sir:

```
$ npx pwned pa mail@example.com
npx: installed 85 in 5.061s
- 
  Id:         http://balockae.online/files/BlackMarketReloaded_users.sql
  Source:     AdHocUrl
  Title:      balockae.online
  Date:       null
  EmailCount: 10547
- 
  Id:         tJmdW6sp
  Source:     Pastebin
  Title:      null
  Date:       2014-08-29T23:08:00Z
  EmailCount: 10124
- 
  Id:         h5zDMduP
  Source:     Pastebin
  Title:      XXXXXX
  Date:       2014-09-22T14:09:00Z
  EmailCount: 377
- 
  Id:         h2KJPWJ9
  Source:     Pastebin
  Title:      null
  Date:       2014-09-22T14:09:00Z
  EmailCount: 10127
- 
  Id:         TSYYzd3d
  Source:     Pastebin
  Title:      null
  Date:       2014-11-02T14:11:00Z
  EmailCount: 7260
```

So it looks like everything is "working as intended". I'm closing the issue and get in touch with Troy.
